// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj7WNjlyfPQJu5BCPh9nidJxKVdSOg52M',
    appId: '1:824287007564:web:509b0662278ba16b1075e9',
    messagingSenderId: '824287007564',
    projectId: 'autoplay-f22b5',
    authDomain: 'autoplay-f22b5.firebaseapp.com',
    storageBucket: 'autoplay-f22b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYPnHUaLuQ7cuwbKOMF9j-QBbDRDnveZE',
    appId: '1:824287007564:android:f5d116080dfd600a1075e9',
    messagingSenderId: '824287007564',
    projectId: 'autoplay-f22b5',
    storageBucket: 'autoplay-f22b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxbPg-d1Taxw7j_fr8CzdR-cwrLjdV9ik',
    appId: '1:824287007564:ios:937137811c14aa261075e9',
    messagingSenderId: '824287007564',
    projectId: 'autoplay-f22b5',
    storageBucket: 'autoplay-f22b5.appspot.com',
    iosBundleId: 'com.example.autoPlayProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxbPg-d1Taxw7j_fr8CzdR-cwrLjdV9ik',
    appId: '1:824287007564:ios:937137811c14aa261075e9',
    messagingSenderId: '824287007564',
    projectId: 'autoplay-f22b5',
    storageBucket: 'autoplay-f22b5.appspot.com',
    iosBundleId: 'com.example.autoPlayProject',
  );
}
